temp01/bbs/urls.py
from django.urls import path

from . import views

app_name = 'bbs'
urlpatterns = [
    # Top Page
    path('', views.IndexView.as_view(), name='index'),
    # Thread List
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # Thread Detail
    # path('<int:pk>/')
]

temp01/temp01/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('bbs/', include('bbs.urls')),
    path('admin/', admin.site.urls),
]

temp01/bbs/models.py
from datetime import datetime

from django.db import models

class Thread(models.Model):
    title = models.CharField('Title', max_length=200, blank=False)
    message = models.TextField('Message', blank=False)
    pub_date = models.DateTimeField('Published date', auto_now_add=True, editable=False)

    class Meta:
        verbose_name = 'thread'

    def __str__(self):
        return self.message

class Comment(models.Model):
    thread = models.ForeignKey(Thread, verbose_name='thread', on_delete=models.CASCADE)
    message = models.CharField('Message', max_length=200, blank=False)
    pub_date = models.DateTimeField('Published date', auto_now_add=True, editable=False)

    class Meta:
        verbose_name = 'comment'

    def __str__(self):
        return self.message

temp01/bbs/views.py
from django.shortcuts import render
from django.utils import timezone
from django.views import generic

from .models import Thread

class IndexView(generic.ListView):
    template_name = 'bbs/index.html'
    context_object_name = 'latest_thread_list'

    def get_queryset(self):
        return Thread.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Thread
    template_name = 'bbs/thread_list.html'

    def get_queryset(self):
        return Thread.objects.filter(
            pub_date__lte=timezone.now()
        )

temp01/bbs/templates/bbs/base.html
<html>
<head>
  <title>{% block content %}{% endblock %}</title>
</head>
<body>
  {% block content %}

  {% endblock %}
</body>
</html>

temp01/bbs/templates/bbs/index.html
<html>
<body>

  {% if latest_thread_list %}
    <ul>
      {% for thread in latest_thread_list %}
        <!-- <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li> -->
        <li><a href="{% url 'bbs:detail' thread.id %}">{{ thread.message }}</a></li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No thread are available.</p>
  {% endif %}
</body>
</html>

temp01/bbs/templates/bbs/thread_list.html
<html>
<body>
  {% block title %}スレッド一覧{% endblock %}

  {% block content %}
  <ul>
  {% for thread in object_list %}
    <li>
      <a href="/thread/{{ thread.id }}/">{{ thread.message }}</a>
      ({{ thread.pub_date|date:"Y年m月d日h時i分s秒" }})
    </li>
  {% endfor %}
  </ul>

  <p><a href="/thread/new/">スレッドの新規作成</a></p>

  <p>{{ page }} / {{ pages }}</p>

  {% if has_previous %}
  <p><a href="/{{ previous }}">前のページ</a></p>
  {% endif %}

  {% if has_next %}
  <p><a href="/{{ next }}">次のページ</a></p>
  {% endif %}

  {% endblock %}
</body>
</html>