temp02/bbs/urls.py
from django.urls import path

from . import views

app_name = 'bbs'
urlpatterns = [
    path('', views.home, name='index'),
    path('<int:pk>/', views.bbs_threads, name='bbs_threads'),
    path('<int:pk>/new/', views.new_thread, name='new_thread'),
]

temp02/temp02/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

from accounts import views as accounts_views
from bbs import views

urlpatterns = [
    path('', include('bbs.urls')),
    path('bbs/', include('bbs.urls')),
    # path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('signup/', accounts_views.signup, name='signup'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path(
        'reset/',
        auth_views.PasswordResetView.as_view(
            template_name='password_reset.html',
            email_template_name='password_reset_email.html',
            subject_template_name='password_reset_subject.txt'
        ),
        name='password_reset'
    ),
    path(
        'reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='password_reset_confirm.html'
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

temp02/accounts/models.py
from django.db import models

# Create your models here.

temp02/bbs/models.py
from django.db import models
from django.contrib.auth.models import User

# 掲示板
class Bbs(models.Model):
    # 名前
    name = models.CharField(max_length=30, unique=True)
    # 説明
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.name

# スレッド
class Thread(models.Model):
    # スレッド名
    name = models.CharField(max_length=255)
    # 最終更新日時
    last_updated = models.DateTimeField(auto_now_add=True)
    # Bbs
    bbs = models.ForeignKey(Bbs, related_name='thread', on_delete=models.CASCADE)
    # スレを建てた人
    starter = models.ForeignKey(User, related_name='thread', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Post(models.Model):
    # 本文
    message = models.TextField(max_length=1024)
    # スレッド名
    thread = models.ForeignKey(Thread, related_name='post', on_delete=models.CASCADE)
    # 書き込んだ時間
    created_at = models.DateTimeField(auto_now_add=True)
    # アップデートした時間
    updated_at = models.DateTimeField(null=True)
    # 誰が書き込んだか
    created_by = models.ForeignKey(User, related_name='post', on_delete=models.CASCADE)
    # 誰がアップデートしたか
    updated_by = models.ForeignKey(User, null=True, related_name='+', on_delete=models.CASCADE)

    def __str__(self):
        return self.message

temp02/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    email = forms.CharField(max_length=254, required=True, widget=forms.EmailInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

temp02/bbs/forms.py
from django import forms

from .models import Thread

class NewThreadForm(forms.ModelForm):
    message = forms.CharField(
        widget=forms.Textarea(
            attrs={'rows': 5, 'placeholder': 'What is on your mind?'}
        ),
        max_length=4000,
        help_text='The max length of the text is 4000.'
    )

    class Meta:
        model = Thread
        fields = ['name', 'message']

temp02/accounts/views.py
from django.contrib.auth import login
# from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect, render

from .forms import SignUpForm

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('bbs:index')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})

temp02/bbs/views.py
# from django.http import Http404
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, redirect, render

from .forms import NewThreadForm
from .models import Bbs, Thread, Post

def home(request):
    bbss = Bbs.objects.all()
    return render(request, 'home.html', {'bbss': bbss})

def bbs_threads(request, pk):
    bbs = get_object_or_404(Bbs, pk=pk)
    return render(request, 'threads.html', {'bbs': bbs})

def new_thread(request, pk):
    bbs = get_object_or_404(Bbs, pk=pk)
    user = User.objects.first()

    if request.method == 'POST':
        form = NewThreadForm(request.POST)
        if form.is_valid():
            thread = form.save(commit=False)
            thread.bbs = bbs
            thread.starter = user
            thread.save()
            post = Post.objects.create(
                message=form.cleaned_data.get('message'),
                thread=thread,
                created_by=user
            )
            return redirect('bbs:bbs_threads', pk=bbs.pk)
    else:
        form = NewThreadForm()

    return render(request, 'new_thread.html', {'bbs': bbs, 'form': form})

temp02/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}BBS{% endblock %}</title>
  <link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/app.css' %}">
  {% block stylesheet %}{% endblock %}
</head>

<body>
  {% block body %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="{% url 'bbs:index' %}">Django BBS</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="mainMenu">
          {% if user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {{ user.username }}
                </a>
                <div class="dropdown-menu dripdown-menu-right" aria-labelledby="userMenu">
                  <a class="dropdown-item" href="#">My account</a>
                  <a class="dropdown-item" href="#">Change password</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                </div>
            </ul>
          {% else %}
            <form class="form-inline ml-auto">
              <a href="{% url 'login' %}" class="btn btn-outline-secondary">Log in</a>
              <a href="{% url 'signup' %}" class="btn btn-primary ml-2">Sign up</a>
            </form>
          {% endif %}
        </div>
      </div>
    </nav>

    <div class="container">
      <ol class="breadcrumb my-4">
        {% block breadcrumb %}
        {% endblock %}
      </ol>
      {% block content %}
      {% endblock %}
    </div>
  {% endblock body %}
  <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

temp02/templates/base_accounts.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block body %}
  <div class="container">
    <h1 class="text-center logo my-4">
      <a href="{% url 'bbs:index' %}">Django BBS</a>
    </h1>
    {% block content %}
    {% endblock %}
  </div>
{% endblock %}

temp02/templates/home.html
{% extends 'base.html' %}

{% block breadcrumb %}
  <li classs="breadcrumb-item active">BBS</li>
{% endblock %}

{% block content %}
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th>BBS</th>
        <th>Posts</th>
        <th>Threads</th>
        <th>Last Post</th>
      </tr>
    </thead>
    <tbody>
      {% for bbs in bbss %}
        <tr>
          <td>
            <a href="{% url 'bbs:bbs_threads' bbs.pk %}">{{ bbs.name }}</a>
            <small class="text-muted d-block">{{ bbs.description }}</small>
          </td>
          <td class="align-middle">0</td>
          <td class="align-middle">0</td>
          <td></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

temp02/templates/includes/form.html
{% load form_tags widget_tweaks %}

{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
      <p{% if forloop.last %} class="mb-0"{% endif %}>{{ error }}</p>
    {% endfor %}
  </div>
{% endif %}

{% for field in form %}
  <div class="form-group">
    {{ field.label_tag }}
    {% render_field field class=field|input_class %}
    {% for error in field.errors %}
      <div class="invalid-feedback">
        {{ error }}
      </div>
    {% endfor %}
    {% if field.help_text %}
      <small class="form-text text-muted">
        {{ field.help_text|safe }}
      </small>
    {% endif %}
  </div>
{% endfor %}

temp02/templates/login.html
{% extends 'base_accounts.html' %}

{% block title %}Log in to Django BBS{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Log in</h3>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary btn-block">Log in</button>
          </form>
        </div>
        <div class="card-footer text-muted text-center">
          New to Django BBS? <a href="{% url 'signup' %}">Sign up</a>
        </div>
      </div>
      <div class="text-center py-2">
        <small>
          <a href="#" class="text-muted">Forgot your password></a>
        </small>
      </div>
    </div>
  </div>
{% endblock %}

temp02/templates/new_thread.html
{% extends 'base.html' %}

{% block title %}Start a New Thread{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'bbs:index' %}">BBS</a></li>
  <li class="breadcrumb-item"><a href="{% url 'bbs:bbs_threads' bbs.pk %}">{{ bbs.name }}</a></li>
  <li class="breadcrumb-item active">New thread</li>
{% endblock %}

{% block content %}
  <form method="post" novalidate>
    {% csrf_token %}
    {% include 'includes/form.html' %}
    <button type="submit" class="btn btn-success">Post</button>
  </form>
{% endblock %}

temp02/templates/password_reset.html
{% extends 'base_accounts.html' %}

{% block title %}Reset your password{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Reset your password</h3>
          <p>Enter your email address and we will send you a link to reset your password.</p>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary btn-block">Send password reset email</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

temp02/templates/password_reset_complete.html
{% extends 'base_accounts.html' %}

{% block title %}Password changed!{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Password changed!</h3>
          <div class="alert alert-success" role="alert">
            You have successfully changed your password! You may now proceed to log in.
          </div>
          <a href="{% url 'login' %}" class="btn btn-secondary btn-block">Return to log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

temp02/templates/password_reset_confirm.html
{% extends 'base_accounts.html' %}

{% block title %}
  {% if validlink %}
    Change password for {{ form.user.username }}
  {% else %}
    Reset your password
  {% endif %}
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <div class="card">
        <div class="card-body">
          {% if validlink %}
            <h3 class="card-title">Change password for @{{ form.user.username }}</h3>
            <form method="post" novalidate>
              {% csrf_token %}
              {% include 'includes/form.html' %}
              <button type="submit" class="btn btn-success btn-block">Change password</button>
            </form>
          {% else %}
            <h3 class="card-title">Reset your password</h3>
            <div class="alert alert-danger" role="alert">
              It looks like you clicked on an invalid password reset link. Please try again.
            </div>
            <a href="{% url 'password_reset' %}" class="btn btn-secondary btn-block">Request a new password reset link</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

temp02/templates/password_reset_done.html
{% extends 'base_accounts.html' %}

{% block title %}Reset your password{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Reset your password</h3>
          <p>Check your email for a link to reset your password. If it doesn't appear within a few minutes, check your spam folder.</p>
          <a href="{% url 'login' %}" class="btn btn-secondary btn-block">Return to log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

temp02/templates/password_reset_email.html
Hi there,

Someone asked for a password reset for the email address {{ email }}.
Follow the link below:
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

In case you forgot your Django BBS username: {{ user.username }}

If clicking the link above doesn't work, please copy and paste the URL in a new browser window instead.

If you've received this mail in error, it's likely that another user entered your email address by mistake while trying to reset a password. If you didn't initiate the request, you don't need to take any further action and can safely disregard this email.

Thanks,

The Django BBS Team

temp02/templates/signup.html
{% extends 'base_accounts.html' %}

{% block title %}Sign up to Django BBS{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Sign up</h3>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary">Create an account</button>
          </form>
        </div>
        <div class="card-footer text-muted text-center">
          Already have an account> <a href={% url 'login' %}>Log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

temp02/templates/threads.html
{% extends 'base.html' %}

{% block title %}
  {{ bbs.name }} - {{ block.super }}
{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'bbs:index' %}">BBS</a></li>
  <li class="breadcrumb-item active">{{ bbs.name }}</li>
{% endblock %}

{% block content %}
  <div class="mb-4">
    <a href="{% url 'bbs:new_thread' bbs.pk %}" class="btn btn-primary">New Thread</a>
  </div>

  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th>Thread Name</th>
        <th>Starter</th>
        <th>Replies</th>
        <th>Views</th>
        <th>Last Update</th>
      </tr>
    </thead>
    <tbody>
      {% for thread in bbs.thread.all %}
        <tr>
          <td>{{ thread.name }}</td>
          <td>{{ thread.starter.username }}</td>
          <td>0</td>
          <td>0</td>
          <td>{{ thread.last_updated }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}